# Generated by Django 2.2.7 on 2019-12-02 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20191125_0408'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comm_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_post',
            field=models.ImageField(upload_to=''),
        ),
    ]
