# Generated by Django 2.2.7 on 2019-12-02 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20191202_0535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comm_count',
        ),
    ]
