# Generated by Django 2.2.7 on 2019-12-02 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_post_comm_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comm_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
