# Generated by Django 2.2.7 on 2019-12-03 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20191203_0617'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
